- name: prepare pipeline
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: "Clone git repo"
    ansible.builtin.git:
      repo: ""
      dest: ""
  - name: "Set up software"
    ansible.builtin.pip:
      name: ""
