- name: Sync data to hdfs
  hosts: storagegroup
  tasks:
    - name: Copy HUMANDB data to HDFS
      ansible.builtin.shell:
        chdir: /home/almalinux/data
        cmd: hdfs dfs -put UP000005640_9606_HUMAN_v4 /UP000005640_9606_HUMAN_v4

    - name: Copy ECOLIDB data to HDFS
      ansible.builtin.shell:
        chdir: /home/almalinux/data
        cmd: hdfs dfs -put UP000000625_83333_ECOLI_v4 /UP000000625_83333_ECOLI_v4
