
- name: Download the CATHDB data
  hosts: workergroup
  tasks:
    - name: Download the CATHDB data
      ansible.builtin.get_url:
        url: "http://bioinfadmin.cs.ucl.ac.uk/downloads/merizo_search/cath_foldclassdb.tar.gz"
        dest: /home/almalinux
        tmp_dest: /home/almalinux/tmp

    - name: Create CATHDB directory
      ansible.builtin.file:
        path: /home/almalinux/cath_foldclassdb
        state: directory
        mode: 0755
        owner: almalinux
        group: almalinux

    - name: Extract the CATHDB archive
      ansible.builtin.unarchive:
        remote_src: true
        src: /home/almalinux/cath_foldclassdb.tar.gz
        dest: /home/almalinux/cath_foldclassdb

    - name: Remove the CATHDB archive
      ansible.builtin.file:
        path: /home/almalinux/cath_foldclassdb.tar.gz
        state: absent
