- name: Download the HUMANDB and ECOLIDB data
  hosts: storagegroup
  tasks:
    - name: Create temp folder for incomplete downloads
      ansible.builtin.file:
        path: /home/almalinux/data/tmp
        state: directory
        mode: 0755

    - name: Download the HUMANDB data
      ansible.builtin.get_url:
        url: "https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000005640_9606_HUMAN_v4.tar"
        dest: /home/almalinux/data
        tmp_dest: /home/almalinux/data/tmp

    - name: Download the ECOLIDB data
      ansible.builtin.get_url:
        url: "https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000000625_83333_ECOLI_v4.tar"
        dest: /home/almalinux/data
        tmp_dest: /home/almalinux/data/tmp

    - name: Remove temp folder
      ansible.builtin.file:
        path: /home/almalinux/data/tmp
        state: absent

- name: Download the CATHDB data
  hosts: workergroup
  tasks:
    - name: Create temp folder for incomplete downloads
      ansible.builtin.file:
        path: /home/almalinux/tmp
        state: directory
        mode: 0755

    - name: Download the CATHDB data
      ansible.builtin.get_url:
        url: "http://bioinfadmin.cs.ucl.ac.uk/downloads/merizo_search/cath_foldclassdb.tar.gz"
        dest: /home/almalinux
        tmp_dest: /home/almalinux/tmp

    - name: Remove temp folder
      ansible.builtin.file:
        path: /home/almalinux/tmp
        state: absent
