- name: Prepare pipeline
  hosts: mgmtgroup, workergroup
  become: true
  become_user: root
  tasks:
    - name: "Distribute application repo"
      ansible.builtin.copy:
        # Copy local files to remote machines (Ansible should run at the root of the project)
        src: "./application"
        dest: "/home/almalinux/mz-application"
    - name: "Download merizo-search repo"
      ansible.builtin.git:
        repo: "https://github.com/psipred/merizo_search"
        dest: "/home/almalinux/merizo_search"
    - name: "Install python dependencies"
      ansible.builtin.pip:
        requirements: "/home/almalinux/mz-application/requirements.txt"
