- name: Prepare pipeline
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: "Clone git repo"
    ansible.builtin.git:
      repo: "https://github.com/CodingPengwing/pipeline.git"
      dest: "/home/almalinux/application"
  - name: "Set up software"
    ansible.builtin.pip:
      name: "/home/almalinux/application"
