- name: Prepare pipeline
  hosts: mgmtgroup, workergroup
  become: true
  become_user: root
  tasks:
    - name: Delete existing application directory
      ansible.builtin.file:
        path: "/home/almalinux/application"
        state: absent
    - name: "Distribute application repo"
      ansible.builtin.copy:
        # Copy local files to remote machines
        src: "{{ playbook_dir }}/../../application/"
        dest: "/home/almalinux/application/"
    - name: "Download merizo-search repo"
      ansible.builtin.git:
        repo: "https://github.com/psipred/merizo_search"
        dest: "/home/almalinux/merizo_search"
    - name: "Install python dependencies"
      ansible.builtin.pip:
        requirements: "/home/almalinux/application/requirements.txt"
