- name: Start the Prometheus server
  hosts: mgmtgroup
  become: true
  become_user: root
  # vars:
  #   prometheus_service_name: prometheus
  #   prometheus_service_state: started
  #   prometheus_service_enabled: true
  tasks:
    - name: Start the Prometheus daemon
      ansible.builtin.shell: nohup prometheus --config.file=/etc/prometheus/prometheus.yml
    - name: Start the NodeExporter daemon
      ansible.builtin.shell: nohup node_exporter
