- name: Start Hadoop cluster
  hosts: mgmtgroup
  vars_files:
    - variables.yaml
  tasks:
    - name: Check if NameNode daemon is running
      ansible.builtin.shell: "ps -ef | grep -w namenode | grep -v grep"
      register: namenode_status
      ignore_errors: true

    - name: Check if ResourceManager daemon is running
      ansible.builtin.shell: "ps -ef | grep -w resourcemanager | grep -v grep"
      register: resourcemanager_status
      ignore_errors: true

    - name: End play if both Hadoop deamons are already running
      meta: end_play
      # Return code 0 means success (grep returned at least 1 process) - daemon is running
      when: namenode_status.rc == 0 and resourcemanager_status.rc == 0

    # If some daemons are not running, we will stop all daemons and start them again
    - name: Stop all Hadoop daemons
      ansible.builtin.shell:
        chdir: "{{ hadoop_sbin_dir }}"
        cmd: ./stop-yarn.sh && ./stop-dfs.sh
      ignore_errors: true
      when: namenode_status.rc == 1 or resourcemanager_status.rc == 1

    - name: Start (or restart) Hadoop daemons
      ansible.builtin.shell:
        chdir: "{{ hadoop_sbin_dir }}"
        cmd: nohup ./start-dfs.sh && nohup ./start-yarn.sh
