- name: Gather the data
  hosts: storagegroup
  tasks:
    - name: Create temp folder for incomplete downloads on larger volume
      ansible.builtin.file:
        path: data/tmp
        state: directory
        mode: "0755"

    - name: Check status of HUMANDB archive
      ansible.builtin.stat:
        path: data/UP000005640_9606_HUMAN_v4.tar
      register: humandb
    - name: Fetch the HUMANDB data
      ansible.builtin.get_url:
        url: "https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000005640_9606_HUMAN_v4.tar"
        dest: data
        tmp_dest: data/tmp
      when: not humandb.stat.exists

    - name: Check status of ECOLIDB archive
      ansible.builtin.stat:
        path: data/UP000000625_83333_ECOLI_v4.tar
      register: ecolidb
    - name: Fetch the ECOLIDB data
      ansible.builtin.get_url:
        url: "https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000000625_83333_ECOLI_v4.tar"
        dest: data
        tmp_dest: data/tmp
      when: not ecolidb.stat.exists

    - name: Check status of CATHDB archive
      ansible.builtin.stat:
        path: data/cath_foldclassdb.tar.gz
      register: cathdb
    - name: Fetch the CATHDB data
      ansible.builtin.get_url:
        url: "http://bioinfadmin.cs.ucl.ac.uk/downloads/merizo_search/cath_foldclassdb.tar.gz"
        dest: data
        tmp_dest: data/tmp
      when: not cathdb.stat.exists

- name: Unpack the data
  hosts: storagegroup
  tasks:
    - name: Unpack the HUMANDB archive
      ansible.builtin.unarchive:
        remote_src: true
        src: /data/almalinux/UP000005640_9606_HUMAN_v4.tar
        dest: data
        creates: data/UP000005640_9606_HUMAN_v4

    - name: Unpack the ECOLIDB archive
      ansible.builtin.unarchive:
        remote_src: true
        src: /data/almalinux/UP000000625_83333_ECOLI_v4.tar
        dest: data
        creates: data/UP000000625_83333_ECOLI_v4

    - name: Unpack the CATHDB archive
      ansible.builtin.unarchive:
        remote_src: true
        src: /data/almalinux/cath_foldclassdb.tar.gz
        dest: data
        creates: data/cath_foldclassdb
