- name: Gather the data
  hosts: storagegroup
  tasks:
    - name: Create temp folder for incomplete downloads on larger volume
      ansible.builtin.file:
        path: /home/almalinux/data/tmp
        state: directory
        mode: "0755"

    - name: Check status of HUMANDB archive
      ansible.builtin.stat:
        path: /home/almalinux/data/UP000005640_9606_HUMAN_v4.tar
      register: humandb
    - name: Fetch the HUMANDB data
      ansible.builtin.get_url:
        url: "https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000005640_9606_HUMAN_v4.tar"
        dest: /home/almalinux/data
        tmp_dest: /home/almalinux/data/tmp
      when: not humandb.stat.exists

    - name: Check status of ECOLIDB archive
      ansible.builtin.stat:
        path: /home/almalinux/data/UP000000625_83333_ECOLI_v4.tar
      register: ecolidb
    - name: Fetch the ECOLIDB data
      ansible.builtin.get_url:
        url: "https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000000625_83333_ECOLI_v4.tar"
        dest: /home/almalinux/data
        tmp_dest: /home/almalinux/data/tmp
      when: not ecolidb.stat.exists

    - name: Check status of CATHDB archive
      ansible.builtin.stat:
        path: /home/almalinux/data/cath_foldclassdb.tar.gz
      register: cathdb
    - name: Fetch the CATHDB data
      ansible.builtin.get_url:
        url: "http://bioinfadmin.cs.ucl.ac.uk/downloads/merizo_search/cath_foldclassdb.tar.gz"
        dest: /home/almalinux/data
        tmp_dest: /home/almalinux/data/tmp
      when: not cathdb.stat.exists

    - name: Remove temp folder
      ansible.builtin.shell:
        cmd: "rm -rf /home/almalinux/data/tmp"
        removes: /home/almalinux/data/tmp

- name: Unpack the data
  hosts: storagegroup
  tasks:
    - name: Create HUMANDB directory
      ansible.builtin.file:
        path: /home/almalinux/data/UP000005640_9606_HUMAN_v4
        state: directory
        mode: "0755"
        owner: almalinux
        group: almalinux
    - name: Count files in the HUMANDB archive
      ansible.builtin.shell:
        cmd: "tar -tf /home/almalinux/data/UP000005640_9606_HUMAN_v4.tar | wc -l"
      register: humandb_original_count
    - name: Count files in the HUMANDB directory
      ansible.builtin.shell:
        cmd: "find /home/almalinux/data/UP000005640_9606_HUMAN_v4/*.gz | wc -l"
      register: humandb_unpacked_count
    - name: Unpack the HUMANDB archive
      ansible.builtin.unarchive:
        remote_src: true
        src: /home/almalinux/data/UP000005640_9606_HUMAN_v4.tar
        dest: /home/almalinux/data/UP000005640_9606_HUMAN_v4
      when: humandb_unpacked_count.stdout != humandb_original_count.stdout

    - name: Count .gz files in HUMANDB directory
      ansible.builtin.shell:
        cmd: "find /home/almalinux/data/UP000005640_9606_HUMAN_v4/*.gz | wc -l"
      count: humandb_gz_count
    - name: Count unpacked files in HUMANDB directory
      ansible.builtin.shell:
        cmd: "find /home/almalinux/data/UP000005640_9606_HUMAN_v4 -type f ! -name '*.gz' | wc -l"
      count: humandb_unpacked_count_before
    - name: Unarchive each .gz file
      ansible.builtin.shell:
        cmd: "ls /home/almalinux/data/UP000005640_9606_HUMAN_v4/*.gz | xargs -n1 gunzip -n"
      when: humandb_gz_count.stdout > humandb_unpacked_count_before.stdout
    - name: Count unpacked files in HUMANDB directory
      ansible.builtin.shell:
        cmd: "find /home/almalinux/data/UP000005640_9606_HUMAN_v4 -type f ! -name '*.gz' | wc -l"
      count: humandb_unpacked_count_after
    - name: Remove the .gz files
      ansible.builtin.shell:
        cmd: "rm *.gz"
      when: humandb_gz_count.stdout == humandb_unpacked_count_after.stdout

    - name: Create ECOLIDB directory
      ansible.builtin.file:
        path: /home/almalinux/data/UP000000625_83333_ECOLI_v4
        state: directory
        mode: "0755"
        owner: almalinux
        group: almalinux
    - name: Count files in the ECOLIDB archive
      ansible.builtin.shell:
        cmd: "tar -tf /home/almalinux/data/UP000000625_83333_ECOLI_v4.tar | wc -l"
      register: ecolidb_original_count
    - name: Count files in the ECOLIDB directory
      ansible.builtin.shell:
        cmd: "find /home/almalinux/data/UP000000625_83333_ECOLI_v4/*.gz | wc -l"
      register: ecolidb_unpacked_count
    - name: Unpack the ECOLIDB archive
      ansible.builtin.unarchive:
        remote_src: true
        src: /home/almalinux/data/UP000000625_83333_ECOLI_v4.tar
        dest: /home/almalinux/data/UP000000625_83333_ECOLI_v4
      when: ecolidb_unpacked_count.stdout != ecolidb_original_count.stdout

    - name: Count .gz files in ECOLIDB directory
      ansible.builtin.shell:
        cmd: "find /home/almalinux/data/UP000000625_83333_ECOLI_v4/*.gz | wc -l"
      count: humandb_gz_count
    - name: Count unpacked files in HUMANDB directory
      ansible.builtin.shell:
        cmd: "find /home/almalinux/data/UP000000625_83333_ECOLI_v4 -type f ! -name '*.gz' | wc -l"
      count: humandb_unpacked_count_before
    - name: Unarchive each .gz file
      ansible.builtin.shell:
        cmd: "ls /home/almalinux/data/UP000000625_83333_ECOLI_v4/*.gz | xargs -n1 gunzip -n"
      when: humandb_gz_count.stdout != humandb_unpacked_count_before.stdout
    - name: Count unpacked files in HUMANDB directory
      ansible.builtin.shell:
        cmd: "find /home/almalinux/data/UP000000625_83333_ECOLI_v4 -type f ! -name '*.gz' | wc -l"
      count: humandb_unpacked_count_after
    - name: Remove the .gz files
      ansible.builtin.shell:
        cmd: "rm *.gz"
      when: humandb_gz_count.stdout == humandb_unpacked_count_after.stdout

    - name: Create CATHDB directory
      ansible.builtin.file:
        path: /home/almalinux/data/cath_foldclassdb
        state: directory
        mode: "0755"
        owner: almalinux
        group: almalinux
    - name: Count files in the CATHDB archive
      ansible.builtin.shell:
        cmd: "tar -tf /home/almalinux/data/cath_foldclassdb.tar.gz | wc -l"
      register: cathdb_original_count
    - name: Count files in the CATHDB directory
      ansible.builtin.shell:
        cmd: "find /home/almalinux/data/cath_foldclassdb -type f -name '*.gz' | wc -l"
      register: cathdb_unpacked_count
    - name: Unpack the CATHDB archive
      ansible.builtin.unarchive:
        remote_src: true
        src: /home/almalinux/data/cath_foldclassdb.tar.gz
        dest: /home/almalinux/data/cath_foldclassdb
      when: cathdb_unpacked_count.stdout < cathdb_original_count.stdout
