- name: Install tools and customize environment
  hosts: all
  become: true
  become_user: root
  vars_files:
    - variables.yaml
  tasks:
    - name: Install dev tools, python3, java
      ansible.builtin.dnf:
        name:
          - glibc-langpack-en
          - vim
          - emacs
          - nano
          - screen
          - tmux
          - net-tools
          - bind-utils
          - htop
          - git
          - python3-devel
          - python3-pip
          - python3-virtualenv
          - patch
          - bzip2
          - make
          - nfs-utils
          - links
          - wget
          - unzip
          - ufw
          - java-11-openjdk
        state: latest

    # Customize locale and time-zone
    - name: Set en-GB localization
      shell: "localectl set-locale en_GB.UTF-8"
    - name: Set time-zone
      shell: "timedatectl set-timezone Europe/London"

    # Customize hosts file and hostname
    - name: Create hosts file
      ansible.builtin.blockinfile:
        block: "{{ lookup('template', 'files/hostfile.j2') }}"
        dest: /etc/hosts
        insertafter: "EOF"
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd

    - name: Preset environment variables
      ansible.builtin.blockinfile:
        path: "{{ working_dir }}/.bashrc"
        block: |
          export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
          export HADOOP_HOME={{ hadoop_home_dir }}
          export HADOOP_INSTALL=$HADOOP_HOME
          export YARN_HOME=$HADOOP_HOME
          export PATH=$PATH:$HADOOP_INSTALL/bin:$HOME/{{ spark_home_dir_name }}/bin
          export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
          export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"
          export HADOOP_CONF_DIR={{ hadoop_config_dir }}
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HADOOP_HOME/lib/native
          export MPLCONFIGDIR=/home/almalinux/.config/matplotlib
        state: present
