- name: Start Hadoop cluster
  hosts: mgmtgroup
  vars_files:
    - variables.yaml
  tasks:
    - name: Check if Hadoop daemons are running
      ansible.builtin.shell: "ps -ef | grep -w {{ item }} | grep -v grep"
      loop: ["namenode", "datanode", "resourcemanager", "nodemanager"]
      ignore_errors: true
      register: daemon_statuses

    - name: Collate daemon statuses
      ansible.builtin.set_fact:
        # All return codes should be 0 if all 4 daemons are running
        hadoop_daemons_stopped: "{{ daemon_statuses.results | selectattr('rc', 'equalto', 1) | list | length > 0 }}"

    # Start Hadoop daemons
    # If any daemon is not running, we will stop all daemons and start them again
    - name: Start (or restart) Hadoop daemons
      ansible.builtin.shell: 
        chdir: "{{ hadoop_sbin_dir }}"
        cmd: |
          ./stop-yarn.sh && 
          ./stop-dfs.sh && 
          nohup ./start-dfs.sh && 
          nohup ./start-yarn.sh
      when: hadoop_daemons_stopped
