- name: Start Hadoop cluster
  hosts: mgmtgroup
  vars_files:
    - variables.yaml
  tasks:
    - name: Check if NameNode daemon is running
      ansible.builtin.shell: "ps -ef | grep -w namenode | grep -v grep"
      register: namenode_status
      ignore_errors: true

    - name: Check if ResourceManager daemon is running
      ansible.builtin.shell: "ps -ef | grep -w resourcemanager | grep -v grep"
      register: resourcemanager_status
      ignore_errors: true

    # Start Hadoop daemons
    # If any daemon is not running, we will stop all daemons and start them again
    - name: Start (or restart) Hadoop daemons
      ansible.builtin.shell: 
        chdir: "{{ hadoop_sbin_dir }}"
        cmd: |
          ./stop-yarn.sh && 
          ./stop-dfs.sh && 
          nohup ./start-dfs.sh && 
          nohup ./start-yarn.sh
      # Return code 0 means success - all daemons are running
      when: namenode_status.rc != 0 or resourcemanager_status.rc != 0
