- name: Update and initial set up
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Update packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Post-update reboot
      reboot:
    - name: Set en-GB localization
      shell: "localectl set-locale en_GB.UTF-8"
    - name: Set time-zone
      shell: "timedatectl set-timezone Europe/London"
    - name: Create hosts file
      ansible.builtin.blockinfile:
        block: "{{ lookup('template', 'files/hostfile.j2') }}"
        dest: /etc/hosts
        insertafter: "EOF"
