- name: Install tools
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install dev tools, python3, java
      ansible.builtin.dnf:
        name:
          - glibc-langpack-en
          - vim
          - emacs
          - nano
          - screen
          - tmux
          - net-tools
          - bind-utils
          - htop
          - git
          - python3-devel
          - python3-pip
          - python3-virtualenv
          - patch
          - bzip2
          - make
          - nfs-utils
          - links
          - wget
          - unzip
          - ufw
          - java-11-openjdk
        state: latest
