- name: Set hostname for management node
  hosts: mgmtgroup
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: mgmtnode
        use: systemd

- name: Set hostname for storage node
  hosts: storagegroup
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: storagenode
        use: systemd

- name: Set hostname for worker nodes
  hosts: workergroup
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{inventory_hostname}}"
        use: systemd
