- name: Set hostname for management node
  hosts: mgmt_group
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: mgmt-node
        use: systemd

- name: Set hostname for storage node
  hosts: storage_group
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: storage-node
        use: systemd

- name: Set hostname for worker nodes
  hosts: worker_group
  become: true
  become_user: root
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: worker-node-{{lookup('ansible.utils.index_of', groups["worker_group"], 'eq', inventory_hostname) + 1 }}
        use: systemd
