---
- import_playbook: c1-update.yaml
- import_playbook: c2-customize.yaml
- import_playbook: c3-set-up-ssh.yaml
- import_playbook: c4-install-hadoop.yaml
- import_playbook: c5-spark-install.yaml
- import_playbook: c6-second-disk.yaml
