---
- import_playbook: c1-update-system.yaml
- import_playbook: c2-customize-environment.yaml
- import_playbook: c3-set-up-ssh.yaml
- import_playbook: c4-install-hadoop.yaml
- import_playbook: c5-install-spark.yaml
- import_playbook: c6-format-storage.yaml
