- name: Install tools and customize environment
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install dev tools, python3, java
      ansible.builtin.dnf:
        name:
          - glibc-langpack-en
          - vim
          - emacs
          - nano
          - screen
          - tmux
          - net-tools
          - bind-utils
          - htop
          - git
          - patch
          - zip
          - bzip2
          - make
          - nfs-utils
          - links
          - wget
          - unzip
          - ufw
          - python3-devel
          - python3-pip
          - python3-virtualenv
          - java-11-openjdk
          - golang
        state: latest

    # Customize locale and time-zone
    - name: Set en-GB localization
      shell: "localectl set-locale en_GB.UTF-8"
    - name: Set time-zone
      shell: "timedatectl set-timezone Europe/London"

    # Customize hosts file and hostname
    - name: Create hosts file
      ansible.builtin.blockinfile:
        block: "{{ lookup('template', 'templates/hostfile.j2') }}"
        dest: /etc/hosts
        insertafter: "EOF"
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
