- name: Install and configure Spark
  hosts: all
  tasks:
    - name: Download Spark .jar
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/spark/spark-3.5.3/spark-3.5.3-bin-hadoop3-scala2.13.tgz"
        dest: /home/almalinux/spark.tgz
    - name: Unpack tgz file
      ansible.builtin.unarchive:
        src: /home/almalinux/spark.tgz
        dest: /home/almalinux/
        remote_src: true
        creates: /home/almalinux/spark-home
        extra_opts:
          - --transform
          - s/.*/spark-home/
    - name: Write config file
      ansible.builtin.template:
        src: files/spark-defaults.conf.j2
        dest: /home/almalinux/spark-home/conf/spark-defaults.conf
