- name: Install and configure Spark
  hosts: all
  vars_files:
    - variables.yaml
  tasks:
    - name: Download Spark .jar
      ansible.builtin.get_url:
        url: "{{ spark_download_url }}"
        dest: "{{ spark_archive_file_path }}"
    - name: Unpack tgz file
      ansible.builtin.unarchive:
        src: "{{ spark_archive_file_path }}"
        dest: "{{ working_dir }}"
        remote_src: true
        creates: "{{ spark_home_dir }}"
        extra_opts:
          - --transform
          - "s/^spark-[a-zA-Z0-9.]*[a-zA-Z0-9]/{{ spark_home_dir_name }}/"
    - name: Write config file
      ansible.builtin.template:
        src: files/spark-defaults.conf.j2
        dest: "{{ spark_config_dir }}/spark-defaults.conf"
